# -*- coding: utf-8 -*-
"""DeepFaceEmotion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QMdXvcYssx9tpnJHsCaea7J-ketDDhvP
"""

# Mount Google Drive to access files stored in your Drive.
# This allows the notebook to read datasets or save outputs directly to Drive.
from google.colab import drive

# Connects your Google Drive to the Colab environment at the folder path: /content/drive
# After running this line, you will be asked to authorize access.
drive.mount('/content/drive')

# Define the main project directory located inside Google Drive.
# This is the folder that contains all the datasets and project files.
base_path = "/content/drive/MyDrive/DeepFaceEmotion"

# Path to the FER2013 CSV file (contains pixel values and labels).
fer_csv_path = f"{base_path}/fer2013.csv"

# Path to the FER2013 ZIP file (used if you need to extract images manually).
fer_zip_path = f"{base_path}/fer2013.zip"

# Path to the extracted RAF-DB dataset folder inside the project directory.
# This folder contains subfolders for each emotion category.
rafdb_output_path = f"{base_path}/RAF-DB"

import os

# Create the RAF-DB directory if it does not already exist.
# This ensures that the extracted files will have a destination folder.
os.makedirs(rafdb_output_path, exist_ok=True)

# Extract the contents of the FER2013 ZIP file into the RAF-DB folder.
# The "-o" flag forces overwrite if files already exist.
!unzip -o "{fer_zip_path}" -d "{rafdb_output_path}"

import pandas as pd

# Load the FER2013 dataset from the CSV file into a Pandas DataFrame.
# The CSV contains pixel values for each image and the corresponding emotion label.
df_fer = pd.read_csv(fer_csv_path)

# Display the first five rows of the dataset to verify that it loaded correctly.
df_fer.head()

# List all files and folders inside the specified directory (recursively).
# This is useful to verify that the RAF-DB dataset was extracted correctly.
!ls -R /content/rafa_db_extracted

# List all files and folders inside the main DeepFaceEmotion directory (recursively).
# This helps verify that all required datasets and project files are correctly stored in the folder.
!ls -R /content/DeepFaceEmotion

# Recursively list all files and subdirectories inside the DeepFaceEmotion folder in Google Drive.
# This is useful to confirm that the project files and datasets exist in the correct location.
!ls -R /content/drive/MyDrive/DeepFaceEmotion

# Recursively list all files and subfolders inside the RAF-DB directory.
# This allows you to verify that the RAF-DB dataset was extracted correctly and is structured properly.
!ls -R /content/drive/MyDrive/DeepFaceEmotion/RAF-DB

# List the first few items inside the RAF-DB test directory.
# Using 'head' limits the output, which is helpful when the folder contains many files.
!ls /content/drive/MyDrive/DeepFaceEmotion/RAF-DB/test | head

# List all items inside the RAF-DB directory (non-recursive).
# This provides a quick overview of the main folders and files in the dataset.
!ls /content/drive/MyDrive/DeepFaceEmotion/RAF-DB

# INSTALL OPENCV FIRST
!pip install opencv-python-headless

# ============================================
# SETUP & IMPORTS
# ============================================

from google.colab import drive
drive.mount('/content/drive')

import os
import numpy as np
import pandas as pd
import glob
import cv2
import matplotlib.pyplot as plt
from tqdm import tqdm
from PIL import Image

from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout, BatchNormalization
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.regularizers import l2
from tensorflow.keras.applications import VGG19, ResNet50

import json

# Base folder in Google Drive where all project files and datasets are stored.
base_path = "/content/drive/MyDrive/DeepFaceEmotion"

# Full path to the FER2013 CSV file containing pixel values and emotion labels.
fer_csv_path = f"{base_path}/fer2013.csv"

# Paths to the RAF-DB training and testing folders.
# These directories contain real-world facial images organized by emotion categories.
raf_train_path = f"{base_path}/RAF-DB/train"
raf_test_path = f"{base_path}/RAF-DB/test"

# Load the FER2013 dataset from the CSV file into a DataFrame.
# The CSV contains pixel values stored as a long space-separated string.
df_fer = pd.read_csv(fer_csv_path)

# Function to convert the pixel string from each row into an actual image file.
# Each image is reshaped to 48x48 pixels (grayscale) and saved as a JPG.
def pixels_to_image(row, save_dir="/content/fer_images"):
    os.makedirs(save_dir, exist_ok=True)  # Create the folder if it doesn't exist
    img_array = np.array(row["pixels"].split(), dtype=np.uint8).reshape(48, 48)
    img_path = os.path.join(save_dir, f"fer_{row.name}.jpg")
    Image.fromarray(img_array).convert("RGB").save(img_path)
    return img_path

# Convert all FER2013 pixel rows into actual image files and store their paths.
df_fer["image_path"] = df_fer.apply(pixels_to_image, axis=1)

# Keep only the image path and label columns, and rename 'emotion' → 'label'
df_fer = df_fer[["image_path", "emotion"]].rename(columns={"emotion": "label"})

# Add a column to indicate that these samples came from the FER2013 dataset.
df_fer["dataset"] = "FER2013"

print("✔ FER2013 images generated successfully")

# Lists to store the file paths and labels for RAF-DB training images.
raf_train_imgs = []
raf_train_labels = []

# Loop through each subfolder inside the RAF-DB train directory.
# Each subfolder represents an emotion category.
for folder in os.listdir(raf_train_path):
    class_path = os.path.join(raf_train_path, folder)
    if os.path.isdir(class_path):

        # Collect all JPG images inside the emotion folder.
        for img in glob.glob(os.path.join(class_path, "*.jpg")):
            raf_train_imgs.append(img)
            raf_train_labels.append(folder)

# Create a DataFrame with image paths and their corresponding labels.
df_raf = pd.DataFrame({"image_path": raf_train_imgs, "label": raf_train_labels})
df_raf["dataset"] = "RAF-DB"  # Mark dataset origin

# Encode text labels (e.g., 'happy', 'angry') into numeric class IDs.
unique_labels = sorted(df_raf["label"].unique())
label_to_num = {label: idx for idx, label in enumerate(unique_labels)}
df_raf["label"] = df_raf["label"].map(label_to_num).astype(int)

print("✔ RAF-DB train loaded successfully")

df_combined = pd.concat([df_fer, df_raf], ignore_index=True)
df_combined["label"] = df_combined["label"].astype(int)

# Split into train/val/test
train_df, test_df = train_test_split(df_combined, test_size=0.15, stratify=df_combined["label"], random_state=42)
train_df, val_df = train_test_split(train_df, test_size=0.15, stratify=train_df["label"], random_state=42)

# Convert labels to string for the generator
train_df["label"] = train_df["label"].astype(str)
val_df["label"] = val_df["label"].astype(str)

print("✔ Dataset combined and split successfully")

# Target image size for all input samples.
# All images will be resized to 96x96 pixels before being fed into the model.
target_img_size = (96, 96)

# Data augmentation for the training set.
# These transformations help increase dataset variability and reduce overfitting.
train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=10,
    width_shift_range=0.1,
    height_shift_range=0.1,
    horizontal_flip=True
)

# Only rescaling for the validation set (no augmentation applied).
val_datagen = ImageDataGenerator(rescale=1./255)

# Create the training generator from the DataFrame.
# Images are read directly from disk using their file paths.
train_generator = train_datagen.flow_from_dataframe(
    train_df,
    x_col="image_path",
    y_col="label",
    target_size=target_img_size,
    batch_size=32,
    class_mode="categorical",
    shuffle=True
)

# Create the validation generator (no shuffling for consistent evaluation).
val_generator = val_datagen.flow_from_dataframe(
    val_df,
    x_col="image_path",
    y_col="label",
    target_size=target_img_size,
    batch_size=32,
    class_mode="categorical",
    shuffle=False
)

# Load the EfficientNetB0 model pre-trained on ImageNet as the feature extractor.
# include_top=False removes the original classification layers so we can add our own.
# input_shape defines the size of the resized images (96x96 RGB).
from tensorflow.keras.applications import EfficientNetB0
base_model = EfficientNetB0(weights='imagenet', include_top=False, input_shape=(96, 96, 3))

from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout, BatchNormalization
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.regularizers import l2

# ============================================================
#   LOAD EfficientNetB0
# ============================================================
base_model = EfficientNetB0(
    weights='imagenet',
    include_top=False,
    input_shape=(96, 96, 3)
)

# ============================================================
#   PARTIAL FINE-TUNING (IMPORTANT!!)
#   - Freeze first ~80% of layers
#   - Unfreeze last 50 layers
# ============================================================

# Step A: Freeze all layers first
for layer in base_model.layers:
    layer.trainable = False

# Step B: Unfreeze the last 80 layers
for layer in base_model.layers[-80:]:
    layer.trainable = True

print("EfficientNetB0 partially unfrozen — last 50 layers are trainable!")

# ============================================================
#   ADD CUSTOM CLASSIFICATION HEAD
# ============================================================
x = base_model.output
x = GlobalAveragePooling2D()(x)

x = Dense(256, activation='relu', kernel_regularizer=l2(0.02))(x)
x = BatchNormalization()(x)
x = Dropout(0.5)(x)

x = Dense(128, activation='relu', kernel_regularizer=l2(0.02))(x)
x = Dropout(0.3)(x)

outputs = Dense(len(train_generator.class_indices), activation='softmax')(x)

model = Model(inputs=base_model.input, outputs=outputs)

# ============================================================
#   COMPILE WITH LOWER LR (CRITICAL FOR FINE-TUNING)
# ============================================================
model.compile(
    optimizer=Adam(learning_rate=1e-5),   # <<<
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

print("✔ Model compiled with Fine-Tuning (LR=1e-5)")

# ============================================================
#   TRAINING THE EFFICIENTNETB0 (AFTER FIXING FREEZE ISSUE)
# ============================================================

# 1) Class Weights (keep as is)
from sklearn.utils.class_weight import compute_class_weight
import numpy as np

classes = np.unique(train_df["label"].astype(int))
weights = compute_class_weight(
    class_weight='balanced',
    classes=classes,
    y=train_df["label"].astype(int)
)
class_weights = dict(enumerate(weights))

# 2) Callbacks (keep as is)
callbacks = [
    EarlyStopping(monitor='val_accuracy', patience=12, restore_best_weights=True),
    ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=4),
]

# 3) TRAIN THE MODEL (UPDATED EPOCHS)
history = model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=25,                     # <<<
    callbacks=callbacks,
    class_weight=class_weights,    # <<<
    verbose=1
)

print("Training Completed Successfully!")

# ---------------------------------------------------------
# Reset the validation generator to ensure predictions
# start from the first batch and maintain correct ordering.
# ---------------------------------------------------------
val_generator.reset()

# ---------------------------------------------------------
# Predict probability scores for each image in the validation set
# using the EfficientNetB0 model.
# ---------------------------------------------------------
y_pred_probs = model.predict(val_generator)

# ---------------------------------------------------------
# Convert predicted probability vectors into final class labels
# by selecting the index of the maximum probability.
# ---------------------------------------------------------
y_pred = np.argmax(y_pred_probs, axis=1)

# ---------------------------------------------------------
# Extract the true class labels from the validation generator.
# This is used to compare predictions vs. actual labels.
# ---------------------------------------------------------
y_true = val_generator.classes

print("✔ Predictions for EfficientNet model completed.")

import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.metrics import confusion_matrix, classification_report

# ==========================================================
# 1) Plot Training & Validation Accuracy (EfficientNetB0)
# ==========================================================
plt.figure(figsize=(10,5))

# Plot accuracy curves from the EfficientNet training history
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')

plt.title("EfficientNetB0 Accuracy Over Epochs")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend()
plt.grid(True)
plt.show()

# ==========================================================
# 2) Plot Training & Validation Loss (EfficientNetB0)
# ==========================================================
plt.figure(figsize=(10,5))

# Plot loss curves from the EfficientNet training history
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')

plt.title("EfficientNetB0 Loss Over Epochs")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.grid(True)
plt.show()

# ==========================================================
# 3) Confusion Matrix (EfficientNetB0)
# ==========================================================

# Compute confusion matrix using true vs. predicted labels
cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(10,7))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')

plt.title("Confusion Matrix - EfficientNetB0")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.show()

# ==========================================================
# 4) Classification Report (EfficientNetB0)
# ==========================================================
print("\n===== EfficientNetB0 Classification Report =====\n")

# Show detailed precision, recall, F1-score for each class
print(classification_report(y_true, y_pred))

# Convert test labels to string (required for categorical mode)
test_df["label"] = test_df["label"].astype(str)

# Create test generator
test_generator = val_datagen.flow_from_dataframe(
    test_df,
    x_col="image_path",
    y_col="label",
    target_size=(96, 96),
    batch_size=32,
    class_mode="categorical",
    shuffle=False
)

test_loss, test_acc = model.evaluate(test_generator)
print(test_acc, test_loss)

# ==========================================================
#   FULL MODEL EVALUATION BLOCK (EfficientNetB0)
#   Includes:
#   - Test Accuracy & Loss
#   - Confusion Matrix (Raw + Normalized)
#   - Per-class Accuracy
#   - Classification Report
#   - ROC-AUC (Multi-class)
#   - Misclassified Images Visualization
#   - Model Parameter Count
#   - Learning Rate Curve
#   - Training Time Per Epoch
# ==========================================================

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, classification_report, roc_auc_score
import time
import tensorflow as tf

# ----------------------------------------------------------
# 1) TEST SET EVALUATION
# ----------------------------------------------------------
print("=== Test Set Evaluation ===")

test_df["label"] = test_df["label"].astype(str)

test_generator = val_datagen.flow_from_dataframe(
    test_df,
    x_col="image_path",
    y_col="label",
    target_size=(96, 96),
    batch_size=32,
    class_mode="categorical",
    shuffle=False
)

test_loss, test_acc = model.evaluate(test_generator)
print(f"Test Accuracy: {test_acc:.4f}")
print(f"Test Loss: {test_loss:.4f}")

# ----------------------------------------------------------
# 2) CONFUSION MATRIX (RAW + NORMALIZED)
# ----------------------------------------------------------
print("\n=== Confusion Matrix ===")

y_true_test = test_generator.classes
y_pred_test_probs = model.predict(test_generator)
y_pred_test = np.argmax(y_pred_test_probs, axis=1)

cm = confusion_matrix(y_true_test, y_pred_test)

plt.figure(figsize=(10,7))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.title("Confusion Matrix - EfficientNetB0")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.show()

# Normalized version
cm_norm = cm.astype("float") / cm.sum(axis=1)[:, np.newaxis]

plt.figure(figsize=(10,7))
sns.heatmap(cm_norm, annot=True, cmap='Blues', fmt=".2f")
plt.title("Normalized Confusion Matrix - EfficientNetB0")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.show()

# ----------------------------------------------------------
# 3) PER-CLASS ACCURACY
# ----------------------------------------------------------
print("\n=== Per-Class Accuracy ===")
per_class_acc = cm.diagonal() / cm.sum(axis=1)
for i, acc in enumerate(per_class_acc):
    print(f"Class {i} Accuracy: {acc:.2f}")

# ----------------------------------------------------------
# 4) CLASSIFICATION REPORT
# ----------------------------------------------------------
print("\n=== Classification Report ===")
print(classification_report(y_true_test, y_pred_test))

# ----------------------------------------------------------
# 5) ROC-AUC (MACRO) FOR MULTI-CLASS
# ----------------------------------------------------------
print("\n=== ROC-AUC (Macro) ===")

y_true_onehot = tf.keras.utils.to_categorical(
    y_true_test,
    num_classes=len(train_generator.class_indices)
)

auc_score = roc_auc_score(
    y_true_onehot,
    y_pred_test_probs,
    multi_class="ovo",
    average="macro"
)

print(f"Macro ROC-AUC: {auc_score:.4f}")

# ----------------------------------------------------------
# 6) MISCLASSIFIED IMAGE EXAMPLES
# ----------------------------------------------------------
print("\n=== Misclassified Images ===")

mis_idx = np.where(y_pred_test != y_true_test)[0][:12]

plt.figure(figsize=(12,8))
for i, idx in enumerate(mis_idx):
    img = plt.imread(test_generator.filepaths[idx])
    plt.subplot(3,4,i+1)
    plt.imshow(img)
    plt.title(f"True: {y_true_test[idx]} | Pred: {y_pred_test[idx]}")
    plt.axis('off')

plt.suptitle("Sample Misclassified Images")
plt.show()

# ----------------------------------------------------------
# 7) MODEL SIZE / PARAMETERS
# ----------------------------------------------------------
print("\n=== Model Parameter Count ===")
total_params = model.count_params()
print(f"Total Trainable & Non-Trainable Parameters: {total_params:,}")

# ----------------------------------------------------------
# 8) LEARNING RATE CURVE (IF AVAILABLE)
# ----------------------------------------------------------
print("\n=== Learning Rate Curve (if tracked) ===")

if "lr" in history.history:
    plt.figure(figsize=(10,5))
    plt.plot(history.history["lr"])
    plt.title("Learning Rate Over Epochs")
    plt.xlabel("Epoch")
    plt.ylabel("Learning Rate")
    plt.grid(True)
    plt.show()
else:
    print("Learning rate not tracked in this training session.")

# ----------------------------------------------------------
# 9) TRAINING TIME PER EPOCH (APPROX)
# ----------------------------------------------------------
print("\n=== Approximate Training Time per Epoch ===")

start = time.time()
model.fit(
    train_generator,
    epochs=1,
    steps_per_epoch=1,
    verbose=0
)
end = time.time()

print(f"Approx. Time per Epoch: {end - start:.2f} seconds")
print("\n=== FULL ANALYSIS COMPLETED ===")

# ============================================================
#   VGG19 MODEL — PART 1
#   (BUILDING + FREEZING + HEAD + COMPILE + TRAIN)
# ============================================================

from tensorflow.keras.applications import VGG19
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout, BatchNormalization
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.regularizers import l2

# ============================================================
#   LOAD VGG19 (PRETRAINED ON IMAGENET)
# ============================================================
vgg_base = VGG19(
    weights="imagenet",
    include_top=False,
    input_shape=(96, 96, 3)
)

print("✔ VGG19 Base Model Loaded")

# ============================================================
#   FREEZE ALL VGG19 LAYERS (FEATURE EXTRACTION)
# ============================================================
for layer in vgg_base.layers:
    layer.trainable = False

print("✔ VGG19 layers frozen")

# ============================================================
#   ADD CUSTOM CLASSIFICATION HEAD
# ============================================================
y = vgg_base.output
y = GlobalAveragePooling2D()(y)

y = Dense(256, activation='relu', kernel_regularizer=l2(0.02))(y)
y = BatchNormalization()(y)
y = Dropout(0.5)(y)

y = Dense(128, activation='relu', kernel_regularizer=l2(0.02))(y)
y = Dropout(0.3)(y)

vgg_outputs = Dense(len(train_generator.class_indices), activation='softmax')(y)

vgg_model = Model(inputs=vgg_base.input, outputs=vgg_outputs)

print("✔ VGG19 Classification Head Attached")

# ============================================================
#   COMPILE VGG19
# ============================================================
vgg_model.compile(
    optimizer=Adam(learning_rate=1e-4),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

print("✔ VGG19 Model Compiled")

# ============================================================
#   TRAIN VGG19
# ============================================================
history_vgg = vgg_model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=25,
    callbacks=callbacks,
    class_weight=class_weights,
    verbose=1
)

print("✔ VGG19 Training Completed!")

# Required imports for evaluation metrics
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, classification_report, roc_auc_score
import tensorflow as tf

# ============================================================
#   RE-CREATE TEST GENERATOR (NEEDED FOR VGG19 EVALUATION)
# ============================================================

test_df["label"] = test_df["label"].astype(str)

test_generator = val_datagen.flow_from_dataframe(
    test_df,
    x_col="image_path",
    y_col="label",
    target_size=(96, 96),
    batch_size=32,
    class_mode="categorical",
    shuffle=False
)

print("✔ Test generator created for VGG19")

# ============================================================
#   VGG19 MODEL — PART 2
#   (PREDICTION + PLOTS + EVALUATION)
# ============================================================

# ============================================================
#   VALIDATION PREDICTIONS
# ============================================================
val_generator.reset()

vgg_pred_probs = vgg_model.predict(val_generator)
vgg_pred = np.argmax(vgg_pred_probs, axis=1)
vgg_true = val_generator.classes

print("✔ VGG19 Predictions Completed")

# ============================================================
#   ACCURACY & LOSS CURVES
# ============================================================
plt.figure(figsize=(10,5))
plt.plot(history_vgg.history['accuracy'], label='Train Accuracy')
plt.plot(history_vgg.history['val_accuracy'], label='Validation Accuracy')
plt.title("VGG19 Accuracy Over Epochs")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend()
plt.grid(True)
plt.show()

plt.figure(figsize=(10,5))
plt.plot(history_vgg.history['loss'], label='Training Loss')
plt.plot(history_vgg.history['val_loss'], label='Validation Loss')
plt.title("VGG19 Loss Over Epochs")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.grid(True)
plt.show()

# ============================================================
#   CONFUSION MATRIX
# ============================================================
cm_vgg = confusion_matrix(vgg_true, vgg_pred)

plt.figure(figsize=(10,7))
sns.heatmap(cm_vgg, annot=True, fmt='d', cmap='Reds')
plt.title("Confusion Matrix - VGG19")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.show()

print("\n===== VGG19 Classification Report =====\n")
print(classification_report(vgg_true, vgg_pred))

# ============================================================
#   TEST SET EVALUATION
# ============================================================
test_generator.reset()

vgg_test_loss, vgg_test_acc = vgg_model.evaluate(test_generator)
print(f"VGG19 Test Accuracy: {vgg_test_acc:.4f}")
print(f"VGG19 Test Loss: {vgg_test_loss:.4f}")

# ============================================================
#   MISCLASSIFIED SAMPLES
# ============================================================
mis_idx_vgg = np.where(vgg_pred != vgg_true)[0][:12]

plt.figure(figsize=(12,8))
for i, idx in enumerate(mis_idx_vgg):
    img = plt.imread(val_generator.filepaths[idx])
    plt.subplot(3,4,i+1)
    plt.imshow(img)
    plt.title(f"True: {vgg_true[idx]} | Pred: {vgg_pred[idx]}")
    plt.axis('off')

plt.suptitle("Sample Misclassified Images — VGG19")
plt.show()

# ============================================================
#   MODEL SIZE (PARAMETER COUNT)
# ============================================================
print("\n=== VGG19 Parameter Count ===")
print(f"Total Parameters: {vgg_model.count_params():,}")